name: CI-CD/Pipeline

on:
  push:
    branches:
        -main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name:checkout
        uses:actions/checkout@v2

      - name:Set up python
        uses:actions/checkout@v2
        with:
            python-version:3.x

      - name:Install independencies
        run: /
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name:Run tests
        run: /
          python -m unittest tests/test.py 


